### ISSUE TITLE
Mangasee search not working

### ISSUE THREAD

**Issue by Spencer-0003** [oae/kaizoku#8] opened 2022-10-23 13:09 UTC
When searching for any Manga via Mangasee I get no results found and this error appears in the logs.

```
[14:04:27.151] ERROR (308): Failed to get available sources: err: Error: Command failed with exit code 1: mangal inline --source Mangasee --query Tomodachi Game -j
X /config/.config/mangal/sources/Mangasee.lua:46: attempt to index a non-table object(nil) with key 'page'
stack traceback:
	/config/.config/mangal/sources/Mangasee.lua:46: in main chunk
	[G]: ?`
```

**Comment by oae** [comment] 2022-10-23 13:12
Duplicate of #5

**Closed** 2022-10-23 13:12 UTC
